config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  root to:'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all.sort_by {|friend| friend.created_at}.reverse
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="label">First Name</label>
      <div class="control">
        <%= form.text_field :first_name, class:"input"%>
      </div>
  </div>

  <div class="field">
    <label class="label">Last Name</label>
      <div class="control">
        <%= form.text_field :last_name, class:"input"%>
      </div>
  </div>

  <div class="field">
    <label class="label">Email</label>
      <div class="control">
        <%= form.text_field :email, class:"input"%>
      </div>
  </div>

  <div class="field">
    <label class="label">Phone</label>
      <div class="control">
        <%= form.text_field :phone, class:"input"%>
      </div>
  </div>

  <div class="field">
    <label class="label">Issue Description</label>
      <div class="control">
        <%= form.text_field :twitter, class:"input"%>
      </div>
  </div>

  <br/>

  <div class="field">
    <div class="control">
      <%= form.submit class:"button is-success", value: "Create ticket" %>
    </div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Issue:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">
<div class="title">Editing Ticket</div>

<br/>

<%= render "form", friend: @friend %>


</div>
</div>

<br>
<div>
  <div class="field is-grouped">
    <p class="control">
      <%= link_to "Show this ticket", @friend, class:"button is-info" %>
    </p>
    <p class="control">
      <%= link_to "Back", friends_path, class:"button" %>
    </p>
  </div>
</div>
</div>

app/views/friends/index.html.erb
<div class="container is-fluid">
<div class="card">

  <div class="card-content">
  <div class="title">Tickets</div>
  <br />
  <div class="table-container">
<table class="table is-striped is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Issue Description</th>
      <th>Created Date</th>
      <th>Update Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @friends.each do |friend| %>
      <tr>

        <td><%= friend.first_name%></td>
        <td><%= friend.last_name%></td>
        <td><%= friend.email%></td>
        <td><%= friend.phone%></td>
        <td><%= friend.twitter%></td>
        <td><%= friend.created_at.strftime('%m-%d-%Y')%></td>
        <td><%= friend.updated_at.strftime('%m-%d-%Y')%></td>


        <td><%= link_to "Show", friend %></td>
        <td><%= link_to "Edit", edit_friend_path(friend) %></td>

      </tr>
    <% end %>

  </tbody>

</table>
<% if user_signed_in? %>

<%= link_to "New ticket", new_friend_path, class:"button is-success" %>

<% end %>
</div>
</div>
</div>
</div>

app/views/friends/new.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">
<div class="title">Add Ticket</div>

<br/>
<%= render "form", friend: @friend %>

<div>

</div>
</div>

</div>
<br/>
<%= link_to "Back to lists", friends_path, class:"button is-link" %>

</div>

app/views/friends/show.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">

    <div class="title">
      <%= @friend.first_name%>
      <%= @friend.last_name%>
    </div>
    <div class="content">
      <strong>Email:</strong>
      <%= @friend.email%>
      <br/>
      <strong>Phone:</strong>
      <%= @friend.phone%>
      <br/>
      <br/>

      <div class="notification is-primary is-light">
      <h2>Issue:</h2>
        <%= @friend.twitter%>
      </div>

      </div>
    </div>
  </div>
<br/>
<div class="field is-grouped">
  <p class="control">
    <%= link_to "Edit this ticket", edit_friend_path(@friend), class:"button is-link"%>
  </p>
  <p class="control">
    <%= link_to "Back to lists", friends_path, class:"button" %>
  </p>
  <p class="control">
    <%= button_to "Delete", @friend, method: :delete, class:"button is-danger" %>
  </p>
</div>
</div>
</div>

app/views/home/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
<div class="container is-fluid">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="https://cdn.jsdelivr.net/gh/declan-haojin/blog-image//duke/FixIt-logo.png" width="130" height="30">
    </a>
    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="false"></span>
      <span aria-hidden="false"></span>
      <span aria-hidden="false"></span>
    </a>
  </div>

  <div id="navMenu" class="navbar-menu">
    <div class="navbar-start">
        <%= link_to 'Home', root_path, class:"navbar-item" %>
        <%= link_to 'Reparing Tickets', friends_path, class:"navbar-item"%>
        <% if user_signed_in? %>
          <%= link_to 'New Ticket', new_friend_path, class:"navbar-item"%>
        <% end %>
        <%= link_to 'About Us', home_about_path, class:"navbar-item"%>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">

            <% if user_signed_in? %>
            <%= link_to 'Profile', edit_user_registration_path, class:"button is-primary"%>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"button is-light"%>
            <% else %>
              <%= link_to 'Sign up', new_user_registration_path, class:"button is-primary"%>
              <%= link_to 'Log in', new_user_session_path, class:"button is-light"%>
            <% end %>
        </div>
      </div>
    </div>
  </div>
<div>
</nav>

app/views/home/about.html.erb
<div class="container is-fluid">
<div class="card">
  <div class="card-content">
<div class="title">About Us</div>
<br/>
<p>FixIt issue tracking system for problems that students notice around campus, such as a cracked dorm window, malfunctioning handicap door button, etc.</p>
</div>
</div>
</div>

app/views/home/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <p class="title">
      Welcome to Duke FixIt!
    </p>
    <br/>
    <p class="subtitle">
      FixIt issue tracking system for problems that students notice around campus, such as a cracked dorm window, malfunctioning handicap door button, etc.
    </p>
  </div>
</section>

app/views/layouts/_notification.html.erb
<div class="notification is-warning">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <title>Duke FixIt</title>
    <link rel="icon" type="image/x-icon" href="https://cdn.jsdelivr.net/gh/declan-haojin/blog-image//duke/FixIt favicon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/0785af7e62.js" crossorigin="anonymous"></script>
  </head>
  <body>

    <%= render 'home/header' %>

    <br/>
    <div class="container">
      <% if notice %>
       <%= render "layouts/notification"%>
      <% end %>

    <%= yield %>

    </div>
  </body>

   </br>
  <footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Duke FixIt</strong> by <a href="https://haojin.li">Haojin Li</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>
</html>